[package]
name = "cli"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[[bin]]
name = "dump-dir"
path = "src/main.rs"

[dependencies]
lib = { path = "../lib" }

# Error framework
errors-lib = { git = "https://github.com/yonasBSD/errors.rs" }
clap = { workspace = true }
miette = { version = "7.6", features = ["fancy"] }
color-eyre = "0.6"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
insta = { version = "1", features = ["toml", "yaml"] }
tempfile = "3"
assert_cmd = "2"
predicates = "3"
